<template>
  <div class="h-screen pt-12 px-24 bg-red-50">
    <div>
      <button class="w-1/2 bg-white ring-4 ring-blue-900 mr-3">
        <p>Programmes</p>
        <p>and grants</p>
        <p>Apply for funding</p>
      </button>

      <button class="w-1/2 bg-white ring-4 ring-blue-900">
        <p>Programmes</p>
        <p>and grants</p>
        <p>Apply for funding</p>
      </button>
    </div>
  </div>
</template>

<script>
export default {
  name: "SectionTwo",
  component: {},
};
</script>

<style></style>
