<template>
  <div class="h-screen pt-12 px-24 bg-red-50">
    <div>
      <button
        class="w-1/3 h-1/2 text-left font-bold text-4xl bg-white ring-4 ring-blue-900 mr-3 py-4 px-3"
      >
        <p class="text-blue-900">Programmes</p>
        <p>and grants</p>
        <p class="text-lg">Apply for funding</p>
      </button>

      <button class="w-1/3 bg-white ring-4 ring-blue-900">
        <p>Programmes</p>
        <p>and grants</p>
        <p>Apply for funding</p>
      </button>
    </div>
  </div>
</template>

<script>
export default {
  name: "SectionTwo",
  component: {},
};
</script>

<style></style>
